config/routes.rb
Rails.application.routes.draw do
  resources :patients
  resources :appointments

  resources :doctors do
    resources :educations, only: [:new, :create, :show, :edit]
  end

  root "pages#home"
  # get "doctor/:id", to: "doctors#show", as: "doctor"
  # get "doctors/new", to: "doctors#new", as: "new_doctor"
  # post "doctors", to: "doctors#create"
  # get "doctors/:id/edit", to: "doctors#edit", as: "edit_doctor"
  # patch "doctor/:id", to: "doctors#update"
  # delete "doctor/:id", to: "doctors#destroy", as: "delete_doctor"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  has_many :educations, dependent: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :title, inclusion: ['Prof', 'Dr']
  validates :speciality, inclusion: ['Dermatologist', 'Pneumologist', 'Cardiologist', 'Dentist', 'GP']
  validates :experience, inclusion: { in: 2..6 }
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :doctor, dependent: :destroy
  validates :score, presence: true , inclusion: { in: 50..100 }
end

# - Score - has to be above 50 and below 100

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :doctors
  has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show]

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
    if @appointment.save
      redirect_to @appointment, notice: 'Appointment was successfully created.'
    else
      render :new
    end
  end

  def index
    @appointments = Appointment.all
  end

  def show
  end

  private

  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  def appointment_params
    params.require(:appointment).permit(:date, :cause, :urgent, :doctor_id, :patient_id)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def index
    @doctors = Doctor.all
    @images = [
      "https://ca.slack-edge.com/T02NE0241-U05VC47MN2C-412d83f67519-512",
      "https://ca.slack-edge.com/T02NE0241-U05USV5HM7E-28be3e669fda-512",
      "https://ca.slack-edge.com/T02NE0241-U05UKKHMXNZ-87a5b75e2103-192",
      "https://ca.slack-edge.com/T02NE0241-U05UM1VT4EN-7328fe9f3fbc-512",
      "https://ca.slack-edge.com/T02NE0241-U05UR60R4UC-222ea601ced6-512",
    ]
  end

  def show
    @doctor = Doctor.find(params[:id])
  end

  def new
    @doctor = Doctor.new # Needed to instantiate the form_with
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to root_path, notice: 'Doctor was successfully created.'
    else
      render :new
    end
  end

  def edit
    @doctor = Doctor.find(params[:id])
  end

  def update
    @doctor = Doctor.find(params[:id])
    if @doctor.update(doctor_params) # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to doctor_path(@doctor)
    else
      render :edit
    end
  end

  def destroy
    @doctor = Doctor.find(params[:id])
    @doctor.destroy
    redirect_to root_path, notice: 'Doctor was successfully deleted.'
  end

  private

  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name, :available, :title, :speciality, :experience)
  end

end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_doctor, only: %i[new create edit update]

  def new
    @education = Education.new
  end

  def create
    @education = Education.new(education_params)
    @education.doctor = @doctor
    @education.save
    redirect_to doctor_path(@doctor)
  end

  def edit
    @education = Education.new
  end

  def update
    if @education.update(education_params) # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to doctor_path(@doctor)
    else
      render :edit
    end
  end


  private

  def set_doctor
    @doctor = Doctor.find(params[:doctor_id])
  end

  def education_params
    params.require(:education).permit(:university, :degree_name, :score)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
  
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[create edit update destroy show]

  def index
    @uncured_patients = Patient.where(cured: false)
  end

  def new
    @patient = Patient.new
  end

  def show
    @appointments = @patient.appointments
  end

  def create
    if @patient.save
      redirect_to patients_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @patient.update(patient_params)
    redirect_to patient_path(@patient)
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_path
  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :insurance, :cured)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointment_helper.rb
module AppointmentHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/index.html.erb
<div class="background" style="background: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), center url(https://images.unsplash.com/photo-1587357327780-c9d724b0bff8?q=80&w=3270&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
  <%= link_to "homepage", root_path, class: "btn btn-ghost" %>
  <%= link_to "back to sicko patients", patients_path, class: "btn btn-ghost" %>

<header class="header_patient">N<i>EW<br></i>APP<i>OIN</i>TME<i>NT</header>
<div class="d-flex justify-content-center">
  <%= link_to "add a new appointment", new_appointment_path, class: "btn btn-ghost" %>
</div>
</div>



<ul>
  <% @appointments.each do |appointment| %>
    <li><%= link_to "#{appointment.cause} #{appointment.urgent} #{appointment.id}", appointment_path(appointment) %></li>
  <% end %>
</ul>

app/views/appointments/new.html.erb
<div class="background" style="background: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), center url(https://images.unsplash.com/photo-1553123428-247ffbd12d90?q=80&w=3270&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
<%= link_to "homepage", root_path, class: "btn btn-ghost" %>
<%= link_to "back to sicko patients", patients_path, class: "btn btn-ghost" %>

<header class="header_appointments">N<i>EW<br></i>APP<i>OINT</i>MENT</header>

<div class="form_appointment">
  <%= simple_form_for(@appointment) do |f| %>
  <%= f.input :date %>
  <%= f.input :cause %>
  <%= f.input :urgent %>
  <%= f.association :doctor, collection: Doctor.where(available: true), label_method: :last_name, value_method: :id, label: "Select Doctor" %>
  <%= f.association :patient, collection: Patient.all, label_method: :last_name, value_method: :id, label: "Select Patient" %>
  <%= f.submit class: "btn btn-ghost" %>
<% end %>

app/views/appointments/show.html.erb
<h1><%= "Cause: #{@appointment.cause}, Urgent: #{@appointment.urgent},
        Appointment-ID: #{@appointment.id},
        Appointment-Date: #{@appointment.date}" %>


<h2><%= link_to "Patient Name: #{@appointment.patient.last_name}", patient_path(@appointment.patient) %></h2>
<h2><%= link_to "Doctor Name: #{@appointment.doctor.last_name}", doctor_path(@appointment.doctor) %></h2>


<%= link_to "back to patient index", patients_path %>

app/views/doctors/edit.html.erb
<div class="background" style="background: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), center url(https://images.unsplash.com/photo-1553123428-247ffbd12d90?q=80&w=3270&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
  <%= link_to "homepage", root_path, class: "btn btn-ghost" %>
  <%= link_to "doctors overview", doctors_path, class: "btn btn-ghost" %>
  <header class="header-patient mt-1">E<i>DI</i>T<br></i>DO<i>CT</i>OR</header>

<div class="form">
  <%= simple_form_for(@doctor) do |f| %>
    <%= f.input :first_name, class: "border-radius:10pc" %>
    <%= f.input :last_name %>
    <%= f.input :title, collection:["Dr", "Prof"]%>
    <%= f.input :speciality, collection: ['Dermatologist', 'Pneumologist', 'Cardiologist', 'Dentist', 'GP']%>
    <%= f.input :experience %>
    <%= f.input :experience %>
    <%= f.input :available %>
    <%= f.submit class: "btn btn-ghost btn-ghost-fix mt-1"%>
  <% end %>
</div>

app/views/doctors/index.html.erb
<div class="background" style="background: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url(https://images.unsplash.com/photo-1477554193778-9562c28588c0?q=80&w=3270&auto=format&f[…]3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
  <%= link_to "add doctor", new_doctor_path, class: "btn btn-ghost" %>
  <%= link_to "homepage", root_path, class: "btn btn-ghost" %>
  <header class="header-patient mt-1" >DO<i>CT</i>ORS<br></i>IN<i>DE</i>X</header>


<div class="form form-fix">
  <% @doctors.each do |doctor| %>
    <%= link_to doctor_path(doctor), class: "no-underline"  do %>
      <div class="card-product">
        <img src= "<%= @images.sample %>"/>
        <div class="card-product-infos">
          <div>
            <h2><%="#{doctor.title} #{doctor.first_name} #{doctor.last_name.capitalize}"%></h2>
            <p><strong><%= doctor.speciality %></strong></p>
            <p><% if doctor.available == true %>
              Doctor is available
              <% else %>
              Doctor not available
              <% end %></p>
            </div>
           <h2><%= link_to "edit", edit_doctor_path(doctor), class: "btn btn-ghost btn-ghost-fix mt-1" %></h2>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

---------

app/views/doctors/new.html.erb
<div class="background" style="background: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), center url(https://images.unsplash.com/photo-1517200578024-62d131797ec8?q=80&w=3428&auto=format&f[…]3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
  <%= link_to "homepage", root_path, class: "btn btn-ghost" %>
  <%= link_to "doctors overview", doctors_path, class: "btn btn-ghost" %>
  <header class="header-patient mt-1">N<i>EW<br></i>DO<i>CT</i>OR</header>


<div class="form">
  <%= simple_form_for(@doctor) do |f| %>
    <%= f.input :first_name, class: "border-radius:10pc" %>
    <%= f.input :last_name %>
    <%= f.input :title, collection:["Dr", "Prof"]%>
    <%= f.input :speciality, collection: ['Dermatologist', 'Pneumologist', 'Cardiologist', 'Dentist', 'GP']%>
    <%= f.input :experience %>
    <%= f.input :available %>
    <%= f.submit class: "btn btn-ghost btn-ghost-fix mt-1"%>
  <% end %>
</div>

app/views/educations/edit.html.erb
<%= simple_form_for [@doctor, @education] do |f| %>
  <%= f.input :university %>
  <%= f.input :degree_name %>
  <%= f.input :score %>

  <%= f.submit %>
<% end %>

app/views/educations/new.html.erb
<%= simple_form_for [@doctor, @education] do |f| %>
  <%= f.input :university %>
  <%= f.input :degree_name %>
  <%= f.input :score %>

  <%= f.submit %>
<% end %>


<%#
  create_table "educations", force: :cascade do |t|
    t.string "university"
    t.string "degree_name"
    t.integer "score"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hospital</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="background" style="background: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https:/images.unsplash.com/photo-1604213410393-89f141bb96b8?ixlib=rb-4.0.3&q=85&fm=jpg&crop=entropy&cs=srgb&dl=su-san-lee-g3PyXO4A0yc-unsplash.jpg);">

<%= link_to "patients", patients_path, class: "btn btn-ghost" %>
<%= link_to "doctors", doctors_path, class: "btn btn-ghost" %>

<div class="container">
  <header class="header">PLA<i>NT<br> BAS</i>ED <br> CLIN</i>IC</header>

  <article class="subline">
    <p>Green Life is alternative medicine clinic <br>specialising in plant based medicine.</p>
  </article>
</div>
</div>

app/views/patients/edit.html.erb
<%= simple_form_for(@patient) do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :insurance %>
  <%= f.input :cured %>
  <%= f.submit %>
<% end %>
<%= link_to "back to index", patients_path %>

app/views/patients/index.html.erb
<div class="background" style="background: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), center url(https://images.unsplash.com/photo-1531875456634-3f5418280d20?q=80&w=3387&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
<%= link_to "homepage", root_path, class: "btn btn-ghost" %>

<%= link_to "add a new patient", new_patient_path, class: "btn btn-ghost" %>
<%= link_to "overview patient appointments", appointments_path, class: "btn btn-ghost" %>

<header class="header">SI<i>CKO<br> PAT</i>IEN</i>TS</header>

<ul>
  <% @uncured_patients.each do |patient| %>
    <li><%= link_to "#{patient.first_name} #{patient.last_name}", patient_path(patient) %></li>
  <% end %>
</ul>

app/views/patients/new.html.erb
<div class="background" style="background: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), center url(https://images.unsplash.com/photo-1553123428-247ffbd12d90?q=80&w=3270&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D);">
<%= link_to "homepage", root_path, class: "btn btn-ghost" %>
<%= link_to "back to sicko patients", patients_path, class: "btn btn-ghost" %>

<header class="header_patient">N<i>EW<br></i>PAT<i>IE</i>NT</header>

<div class="form">
  <%= simple_form_for(@patient) do |f| %>
  <%= f.input :first_name, class: "border-radius:10px" %>
  <%= f.input :last_name %>
  <%= f.input :insurance, collection:["Private", "Public"] %>
  <%= f.input :cured %>
  <%= f.submit class: "btn btn-ghost" %>
<% end %>
</div>

app/views/patients/show.html.erb
<h1><%= "#{@patient.first_name} #{@patient.last_name}" %></h1>


<h1>Index of all coming appointments</h1>

<ul>
  <% @appointments.each do |appointment| %>
    <li><%= "on #{appointment.date} with #{appointment.doctor.last_name}" %></li>
  <% end %>
</ul>


<%= link_to "back to index", patients_path %>
<%= link_to "edit patient", edit_patient_path %>
<%= link_to "Delete", patient_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>